### ISSUE TITLE
Can't def vars in REPL after Virgil reloads

### ISSUE THREAD

**Issue by schmee** [clj-commons/virgil#20]
I've come across a weird issue. To reproduce, create a new folder with the following files:

project.clj:
```
(defproject virgil-debug "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.9.0"]]
  :profiles {:dev {:plugins [[lein-virgil "0.1.7"]]
                   :source-paths ["env/dev"]
                   :java-source-paths ["java"]}})
```
env/dev/user.clj
```
(ns user)
```

java/Foo.java
```
package foo.bar;

public class Foo {
  // Whatever
}
```

Now, when you start a REPL:
```
Compiling 1 source files to /Users/<somepath>/clojure/virgil-debug/target/classes
nREPL server started on port 54024 on host 127.0.0.1 - nrepl://127.0.0.1:54024
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_92-b14

recompiling all files in ["/Users/<somepath>/clojure/virgil-debug/java"]

user=> :reloading (user)

user=> (do (def a 1) (class a))
#<Class@68e818cc clojure.lang.Var$Unbound>
```

To fix the issue, simply comment out `(ns user)` in `user.clj`

```
user=> (do (def a 1) (class a))
#<Class@3a079870 java.lang.Long>
```

I thought that this was some sort of race condition because the REPL inits in the `user` ns, but the issue remains even if you set `:repl-options {:init-ns some.other.ns}`. Probably related to https://github.com/ztellman/virgil/issues/15 also.

**Comment by schmee** [comment]
FWIW, I've worked around this issue by not using the lein plugin. Instead, I've added the library itself as a dev dependency and call `virgil.compile/compile-all-java` with my Java source paths manually in my REPL reload function.

**Comment by aiba** [comment]
@schmee can you elaborate on how you set that up?

I would like to invoke a `virgil.compile/compile-all-java` whenever I do a `clojure.tools.namespace.repl/reset`.  However, `clojure.tools.namespace` tracks clojure namespace deps, but not java deps, so the clojure namespaces that import the recompiled java classes do not get reloaded.  I'm curious if you have a solution for this.

**Comment by schmee** [comment]
@aiba I worked around that by simply calling `refresh-all` instead of `refresh` whenever I needed to reload my Java code. The project I was working on was quite small so it was not a problem in my case, but it's certainly not ideal if you're working on a larger project. Since it solved my use-case I haven't looked further into the problem.

**Comment by 4mitch** [comment]
The same situation, with [lein-virgil "0.1.9"] and (ns user) in user.clj repl has broken ```def``` which returns clojure.lang.Var$Unbound 
:(

**Comment by alexander-yakushev** [comment]
I suppose this is no longer relevant as Virgil doesn't reload anything automatically anymore.
