### ISSUE TITLE
defonce does not persist values across reloads

### ISSUE THREAD

**Issue by EmmanuelOga** [clj-commons/virgil#32]
Once virgil notices a change on a .java file it recompiles everything on the folder and reloads every namespace.
Any value inside a `defonce` is lost.

I was wondering what's would be a good solution here?

Other than "fixing" the issue (I assume would require additional machinery), other options that can think;
- Supplying a list of namespaces that shouldn't be reloaded when recompiling.
- Supplying some sort of on-stop/on-start method per namespace (like shadow-cljs or figwheel do) such that I can clear/reset the value (in my case it is holding an atom for the PID of a server, the server should be stopped before the NS is reloaded).

Let me know your thoughts!

**Comment by alexander-yakushev** [comment]
Don't know if this is relevant anymore, but with the new API, namespaces aren't automatically reload anymore. You would either have to call `tools.namespace` manually or provide it as a hook to `watch-and-recompile`. In either case, you will be in control of which namespaces are reloaded.
